edited unit conversion factor explanation
lbl-srg/obc pull request #39
Opened 2018-09-14 21:14 UTC by milicag

Minor edit, see below.

2018-09-14 21:15 UTC, milicag commented
@mwetter Ready for review.

2018-09-15 05:00 UTC, mwetter requested changes

2018-09-15 05:00 UTC, mwetter commented on specification/source/verification.rst
> +(or kelvin) to one degree Fahrnheit of temperature difference.
Please correct typo.

2018-09-15 05:09 UTC, milicag commented
@mwetter Done.

2018-09-17 19:56 UTC, merged