Issue 6 glossary
lbl-srg/obc pull request #7
Opened 2017-05-04 16:47 UTC by milicag

I've initiated a glossary file. It is rather incomplete at this point, since it seems like the terms are still not very clear to me.

2017-05-04 16:59 UTC, milicag commented on specification/source/glossary.rst
> +.. _sec_glossary:
Do we want to have this as a separate file?

2017-05-04 18:28 UTC, mwetter commented on specification/source/glossary.rst
> +.. _sec_glossary:
yes, best is in a separate file

2017-05-04 18:28 UTC, mwetter commented on specification/source/glossary.rst
> +----------------------
Underlines should be the same length as the title, otherwise sphinxdoc complains

2017-05-04 18:30 UTC, mwetter commented on specification/source/glossary.rst
> +      A control sequence specified by ASHRAE Guidline 36
typo

2017-05-04 18:33 UTC, mwetter commented on specification/source/glossary.rst
> +      fixme: should satisfy requrements arising from any of the validation use cases
The Functional Verification Tool is a software that takes as an input the control sequence in CDL, requirements expressed in CDL, a list of I/O connections, and a configuration file, and then tests whether the measured control signals satisfy the requirements, violate them, or whether some requirements remain untested.

2017-05-04 18:33 UTC, mwetter requested changes
See inline comments.

2017-05-06 05:43 UTC, merged

2017-05-08 17:00 UTC, milicag commented on specification/source/glossary.rst
> +     that is used to express control sequences and requirements.
@mwetter What are control requirements? Is a sequence from the G36 library at the same time a requirement? Thanks!

2017-05-08 17:08 UTC, mwetter commented on specification/source/glossary.rst
> +     that is used to express control sequences and requirements.
A requirement is something that is tested and either passes, fails, or is untested. For example, a requirement would be that the actual actuation signal is within 2% of the signal computed using the CDL representation of a sequence, provided that they both receive the same input data. See also www.ep.liu.se/ecp/118/067/ecp15118625.pdf

2017-05-08 17:23 UTC, milicag commented on specification/source/glossary.rst
> +     that is used to express control sequences and requirements.
This seems worth adding to the glossary. I can add it on the master if you agree.

2017-05-08 17:28 UTC, mwetter commented
Please make a pull request.

On Mon, May 8, 2017 at 10:23 AM, milicag <notifications@github.com> wrote:

> *@milicag* commented on this pull request.
> ------------------------------
>
> In specification/source/glossary.rst
> <https://github.com/lbl-srg/obc/pull/7#discussion_r115303678>:
>
> > @@ -0,0 +1,50 @@
> +.. _sec_glossary:
> +
> +Glossary
> +--------
> +
> +This section provides definitions for abbreviations and terms introduced in
> +the Open Building Controls project.
> +
> +.. If you add new entries, keep the alphabetical sorting.
> +
> +.. glossary::
> +
> +   Controls Description Language
> +     The Control Description Language (CDL) is the language
> +     that is used to express control sequences and requirements.
>
> This seems worth adding to the glossary. I can add it on the master if you
> agree.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lbl-srg/obc/pull/7#discussion_r115303678>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABRHuN3dfheJ3k-XHRcqp_jJVNp4Mcn-ks5r30-BgaJpZM4NQ79D>
> .
>